### ISSUE TITLE
[Defect] Reviews cannot have score of 0

### ISSUE THREAD

**Issue by katiehrenchir** [tannerstephens/cerner-food-reviews#2]
Reviews cannot have a score of 0 - this is counted as not completing the form. 

![Screen Shot 2020-02-17 at 2 15 46 PM](https://user-images.githubusercontent.com/8648995/74683973-1e142a80-5190-11ea-885d-c0258a11753f.png)

A score of 0 is valid and the form should reflect that

**Comment by tannerstephens** [comment]
This is fixed in 3011785
